### ISSUE TITLE
JSON Parsing error when querying Crypto

### ISSUE THREAD

**Issue by atrusinov** [vslee/IEXSharp#109]
Hello,

It appears that when I try to make a call to get the price for any of the cryptocurrencies the json serialization fails:

Example: 

 var response = iexCloudClient.Crypto.PriceAsync("ETHUSD").Result;

returns :
JsonException: The JSON value could not be converted to System.Decimal. Path: $.price | LineNumber: 0 | BytePositionInLine: 18.

Do you have any fix on that?

**Comment by atrusinov** [comment]
It appears that trying to parse a decimal of "2396.74" in the DecimalConverter fails due to the format. Parsing "2396,74" works

**Comment by vslee** [comment]
Looks like you're in a country where the `.` and `,` are reversed from the US way. So I cannot test / reproduce your bug. But I did post a new commit which may have fixed it. You can try the [latest pre-release](https://github.com/vslee/IEXSharp/wiki/Use-GitHub-Packages-with-Visual-Studio), and if it still doesn't work, re-open this issue.

**Comment by Rodrico** [comment]
Hi, I was facing same issue and while I wasn't able to find mentioned pre-release version in your nuget feed I managed to workaround it by setting global culture to Invariant, you can just put
`CultureInfo.DefaultThreadCurrentCulture = CultureInfo.InvariantCulture;`
`CultureInfo.DefaultThreadCurrentUICulture = CultureInfo.InvariantCulture;`
somewhere during init phase of your application.

If you'd like to verify it's fixed in prerelease you could do it in a reverse way and set there `new CultureInfo("cs-CZ")` instead of invariant and that should reproduce the issue.

**Comment by vslee** [comment]
v2.9.0 is out now, if you'd like to try that
